apps_directory: C:\Users\user/.config/desktop_compose/apps
templates_directory: C:\Users\user/.config/desktop_compose/templates
zone_configs_directory: C:\Users\user/.config/desktop_compose/zone_configs
